export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const FETCH_MATCHES_BEGIN = "FETCH_MATCHES_BEGIN";
export const FETCH_MATCHES_SUCCESS = "FETCH_MATCHES_SUCCESS";
export const FETCH_MATCHES_FAILURE = "FETCH_MATCHES_FAILURE";

export const FETCH_DELEGABLE_MATCHES_BEGIN = "FETCH_DELEGABLE_MATCHES_BEGIN";
export const FETCH_DELEGABLE_MATCHES_SUCCESS = "FETCH_DELEGABLE_MATCHES_SUCCESS";
export const FETCH_DELEGABLE_MATCHES_FAILURE = "FETCH_DELEGABLE_MATCHES_FAILURE";

export const FETCH_ELIGIBLE_REFS_BEGIN = "FETCH_ELIGIBLE_REFS_BEGIN";
export const FETCH_ELIGIBLE_REFS_SUCCESS = "FETCH_ELIGIBLE_REFS_SUCCESS";
export const FETCH_ELIGIBLE_REFS_FAILURE = "FETCH_ELIGIBLE_REFS_FAILURE";
