-- Generate Mocked data for MATCHINFO table
insert into MatchInfo (TeamAID, TeamBID, Venue) values (154, 231, 'Zhentou');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (131, 331, 'Thika');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (217, 316, 'Dzerzhinsk');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (176, 67, 'Monte da Pedra');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (110, 191, 'Bender');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (16, 306, 'Jāmpur');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (142, 58, 'Blangpulo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (63, 136, 'Vilkija');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (122, 346, 'Gamut');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (32, 209, 'Korçë');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (367, 306, 'Fort Myers');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (222, 104, 'Ashford');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (193, 321, 'Mumen');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (284, 371, 'Perosinho');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (305, 234, 'Arenas');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (219, 387, 'Aygeshat');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (380, 31, 'San Antonio');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (233, 166, 'Fagatogo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (191, 312, 'Vukovije Donje');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (157, 345, 'Všenory');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (29, 174, 'Shuangxikou');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (206, 327, 'Eksjö');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (354, 88, 'London');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (283, 291, 'Gudja');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (289, 298, 'Gyangqai');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (101, 79, 'Presidente Venceslau');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (64, 341, 'Iwade');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (47, 220, 'Tulusmulyo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (283, 44, 'Upernavik');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (86, 107, 'Malārd');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (171, 236, 'Zengtian');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (193, 318, 'Laoshawan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (392, 229, 'Bukbatang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (196, 240, 'Almirante Tamandaré');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (45, 134, 'Ban Kruat');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (191, 159, 'Nīshābūr');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (393, 60, 'Jenggawah');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (22, 122, 'Ibirité');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (144, 356, 'Orlovat');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (191, 95, 'Umpak');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (193, 133, 'Kihangara');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (376, 393, 'Mabamba');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (66, 190, 'Sztum');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (70, 156, 'Tuanai');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (287, 203, 'Centar Župa');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (369, 155, 'Bianzhuang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (105, 331, 'Boro');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (234, 232, 'Ismailia');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (370, 20, 'Jargalant');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (10, 380, 'Naka');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (83, 332, 'Medveđa');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (32, 95, 'Carcassonne');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (248, 5, 'Gryazovets');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (166, 149, 'K’ulashi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (29, 256, 'Carmo do Cajuru');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (250, 144, 'Litvínov');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (400, 355, 'Sukasari');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (315, 100, 'Solna');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (136, 286, 'Sittwe');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (36, 388, 'Shakhta');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (307, 305, 'Milot');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (120, 164, 'Nyeri');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (300, 234, 'Kolambugan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (369, 272, 'Liuqiao');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (289, 172, 'La Argentina');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (19, 283, 'Brody');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (306, 316, 'Ruda Maleniecka');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (210, 395, 'Krasnoarmeysk');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (295, 386, 'Claremorris');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (50, 10, 'Dacun');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (170, 138, 'Timbiras');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (257, 151, 'Cabodiongan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (124, 125, 'Merefa');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (229, 128, 'Jujur');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (194, 66, 'Gayam');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (35, 373, 'Quận Tân Phú');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (73, 348, 'Tabango');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (67, 266, 'El Cubolero');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (89, 158, 'Aydūn');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (398, 127, 'Da’an');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (203, 184, 'Lubin');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (203, 310, 'Wręczyca Wielka');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (282, 98, 'Embu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (372, 66, 'Sumberdangdang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (75, 43, 'Quince Mil');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (223, 28, 'Cagnes-sur-Mer');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (303, 144, 'Open Stage');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (399, 205, 'Ramalhal');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (139, 247, 'Guihuaquan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (121, 333, 'Al Jahrā’');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (281, 312, 'Ouro Sogui');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (347, 54, 'Binhe');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (188, 383, 'Arazane');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (128, 252, 'Penanggal');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (260, 16, 'Nanxing');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (250, 330, 'Batasan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (41, 97, 'Birmingham');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (136, 328, 'Shanting');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (2, 275, 'Concordia');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (64, 356, 'Malainen Luma');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (50, 314, 'Esperança');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (353, 379, 'Pakong');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (295, 277, 'Qingzhou');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (19, 358, 'Jeminay');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (108, 73, 'Emiliano Zapata');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (74, 238, 'Linqu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (199, 213, 'Malveira');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (29, 222, 'Maying');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (27, 358, 'Aboisso');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (216, 369, 'Taposan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (241, 57, 'Rotterdam');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (332, 69, 'Cambebba');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (113, 178, 'Xinzhuang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (15, 252, 'Tall Abyaḑ');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (10, 340, 'Baruta');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (191, 18, 'Miedzichowo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (111, 182, 'San Ignacio de Velasco');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (156, 30, 'Katunayaka');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (374, 246, 'Madrid');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (154, 171, 'Gostimë');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (258, 50, 'Yishi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (384, 126, 'Fryazino');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (140, 105, 'Milwaukee');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (285, 154, 'Huangli');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (347, 82, 'Izumo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (225, 217, 'Romblon');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (159, 146, 'Dibba Al-Fujairah');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (82, 325, 'Shchëkino');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (65, 257, 'Mrongi Daja');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (324, 397, 'Ouaoula');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (345, 30, 'Zainsk');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (88, 62, 'Mthatha');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (48, 163, 'Göteborg');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (146, 72, 'Netrakona');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (78, 50, 'Weiting');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (341, 162, 'Launceston');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (310, 25, 'Rusocice');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (347, 153, 'Armen');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (302, 179, 'Donskoye');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (361, 186, 'Pulau Pinang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (157, 151, 'Hongyanxi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (105, 311, 'Shibīn al Kawm');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (111, 397, 'Dalianhe');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (181, 144, 'Sevilla');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (98, 161, 'Jastrowie');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (186, 261, 'Blang Dalam');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (188, 173, 'Dachnoye');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (190, 291, 'Aktau');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (111, 30, 'Potikosin');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (347, 276, 'Zaozhuang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (62, 390, 'May Pen');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (303, 143, 'Enskededalen');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (292, 163, 'Kangar');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (152, 351, 'Komsomol’skiy');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (112, 335, 'Lages');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (364, 10, 'Hengbanqiao');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (135, 28, 'Masape');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (6, 321, 'Roskoshnyy');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (292, 117, 'Bukovany');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (261, 330, 'Qitai');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (277, 339, 'Shiyaogou');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (74, 143, 'Lat Yao');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (276, 247, 'Xuelu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (129, 288, 'Biyan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (113, 217, 'Mora');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (133, 137, 'Mendez-Nuñez');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (337, 27, 'Sosnovka');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (275, 385, 'Manjo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (180, 307, 'Lazaro Cardenas');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (190, 125, 'Kikerino');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (23, 270, 'Načeradec');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (297, 145, 'Palayan City');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (137, 352, 'Cihaur');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (52, 289, 'Pessac');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (142, 235, 'Tver');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (215, 299, 'Płońsk');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (59, 96, 'Silvino Lobos');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (182, 275, 'Hanban');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (63, 294, 'Nara-shi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (269, 344, 'Bauru');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (267, 258, 'Rouen');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (372, 24, 'Alastaro');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (272, 179, 'Tominian');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (32, 80, 'Iberia');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (31, 165, 'Krajan Karangwage');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (313, 321, 'Bom Jesus da Lapa');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (55, 393, 'Jamshoro');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (90, 100, 'Massenya');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (188, 212, 'Kaiaf');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (190, 105, 'Hake');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (332, 194, 'Tongzi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (40, 335, 'Pacajus');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (28, 203, 'Madīnat ash Shamāl');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (162, 375, 'Buruanga');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (298, 158, 'La Rochelle');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (29, 137, 'Bobrowice');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (397, 248, 'Shah Alam');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (195, 59, 'Bīr Zayt');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (355, 200, 'Jiandou');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (278, 373, 'Vienna');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (283, 387, 'Ostroróg');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (114, 91, 'Gręboszów');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (387, 372, 'Iţsā');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (176, 123, 'Bilao');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (349, 80, 'Chengxiang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (291, 145, 'Tiên Phước');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (173, 148, 'Basīrpur');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (51, 362, 'Mboto');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (239, 54, 'Phra Nakhon Si Ayutthaya');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (55, 160, 'Likhovskoy');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (187, 93, 'Capioví');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (341, 64, 'Honglong');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (365, 118, 'Denver');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (204, 323, 'Dalo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (166, 327, 'Qidi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (125, 133, 'Phu Khiao');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (184, 384, 'Meijiang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (168, 265, 'Vanves');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (391, 110, 'Luoxi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (29, 140, 'Zhenxi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (43, 27, 'Turenki');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (82, 6, 'Fayzabad');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (41, 38, 'Santa Bárbara');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (32, 393, 'Lương Bằng');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (71, 329, 'Jarānwāla');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (386, 321, 'Sebulu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (227, 353, 'Datartua');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (267, 188, 'Maszkienice');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (254, 226, 'Kashiwa');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (377, 214, 'Karangduren Dua');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (128, 113, 'Sadananya');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (87, 145, 'Wangong');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (50, 56, 'Yujiao');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (158, 279, 'Gelsenkirchen');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (15, 101, 'Privlaka');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (18, 96, 'Kousa');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (177, 384, 'Futian');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (216, 51, 'Dordrecht');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (309, 97, 'Przelewice');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (97, 340, 'Tomaszów Mazowiecki');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (323, 185, 'Krasnokuts’k');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (27, 194, 'Frederiksberg');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (246, 380, 'Pernå');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (293, 205, 'Lope de Vega');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (351, 57, 'Göteborg');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (168, 7, 'Sarnaki');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (194, 257, 'Velille');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (343, 350, 'Sanlanbahai');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (233, 249, 'Lumatil');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (5, 356, 'Huoli');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (207, 289, 'Lubango');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (199, 153, 'Piracuruca');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (321, 10, 'Växjö');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (227, 290, 'Shibi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (287, 313, 'Saint-Louis du Sud');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (296, 8, 'Swan Hills');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (229, 208, 'Mindupok');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (73, 368, 'Chumpi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (223, 14, 'Paris 19');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (29, 139, 'Łomazy');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (287, 262, 'Napoles');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (232, 164, 'Göteborg');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (34, 396, 'Strawberry Hills');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (42, 156, 'Kétou');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (27, 213, 'Zhifang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (210, 19, 'Taoyuan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (375, 345, 'Gangjia');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (151, 98, 'Armenia');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (188, 389, 'Proença-a-Nova');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (40, 147, 'Pochinok');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (267, 317, 'Myingyan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (45, 130, 'Bằng Lũng');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (327, 99, 'Borovo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (38, 234, 'Sísion');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (6, 235, 'Lianzhou');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (319, 224, 'Niška Banja');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (374, 366, 'Sui’an');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (142, 170, 'Kungsbacka');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (136, 155, 'Merapit');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (144, 88, 'Domašinec');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (8, 213, 'Gondomar');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (307, 296, 'Hagonoy');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (140, 134, 'Bāglung');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (307, 340, 'Vichuga');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (25, 23, 'Losevo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (201, 123, 'Santa Cruz de El Seibo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (174, 113, 'Netrakona');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (147, 168, 'Apongo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (29, 175, 'Kristianstad');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (5, 218, 'Södertälje');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (141, 219, 'Erími');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (141, 362, 'Klášterec nad Ohří');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (247, 245, 'Jagupit');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (93, 366, 'Svojat');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (258, 77, 'Wartburg');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (228, 234, 'Prínos');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (35, 99, 'Tayabamba');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (113, 375, 'San Joaquin');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (192, 206, 'Pechenizhyn');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (29, 19, 'Tanjungrejo Lor');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (106, 26, 'Skien');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (316, 344, 'General Vedia');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (177, 44, 'Tsowkêy');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (34, 169, 'Hatogaya-honchō');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (104, 378, 'Oyonnax');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (72, 345, 'Arrabal');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (70, 49, 'Daxing');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (138, 310, 'Al Wardānīn');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (153, 28, 'Peddie');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (82, 115, 'Washington');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (288, 379, 'Wuyo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (137, 394, 'Sam Phran');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (279, 368, 'Horta');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (13, 128, 'Timashëvsk');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (199, 26, 'Oesain');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (304, 395, 'Batiano');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (186, 64, 'Kindu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (120, 65, 'Boden');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (350, 392, 'Huangqu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (112, 232, 'Xiamayu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (179, 195, 'Chonghe');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (308, 332, 'Monsanto');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (248, 293, 'Pasar Kulon');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (352, 201, 'Xunhe');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (279, 135, 'Maishi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (284, 386, 'Hawassa');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (37, 384, 'Alofi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (204, 358, 'Dinititi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (73, 77, 'Guri-si');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (226, 233, 'Pingdingbu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (358, 353, 'Shirochanka');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (13, 123, 'Prochowice');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (231, 147, 'Adstock');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (178, 31, 'Oslo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (273, 379, 'Narutō');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (329, 281, 'Yong’an');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (320, 244, 'Serednye Vodyane');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (273, 133, 'Jaguaribe');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (89, 227, 'Mirnyy');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (244, 380, 'Turija');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (300, 371, 'Idtig');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (156, 195, 'Caluquembe');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (25, 147, 'København');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (364, 348, 'Mayfa‘ah');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (287, 68, 'كاف الجاع');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (343, 300, 'Kokkinóchoma');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (97, 319, 'Portela');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (106, 257, 'Muaratiga');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (204, 350, 'Åkersberga');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (92, 146, 'Albergaria');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (115, 317, 'Ilha Solteira');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (310, 247, 'Yicheng');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (347, 395, 'Peruíbe');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (281, 260, 'Yevlakh');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (320, 173, 'Montería');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (244, 39, 'Malangabang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (22, 358, 'Jincheng');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (379, 55, 'Lukolela');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (176, 380, 'Ryazanskiy');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (137, 280, 'Toledo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (321, 37, 'Rongkou');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (307, 167, 'San Agustín');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (83, 357, 'Argotirto Krajan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (99, 68, 'Despotovac');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (169, 80, 'Veldhoven');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (105, 312, 'Somovo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (111, 11, 'Pavlodol’skaya');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (300, 78, 'Rodionovo-Nesvetaiskoye');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (68, 335, 'Nanniu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (187, 180, 'Tumba');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (96, 61, 'Babat');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (63, 261, 'Bandung');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (185, 229, 'Raczki');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (19, 163, 'Alfenas');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (397, 315, 'Francisco J Mujica');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (364, 251, 'Damnica');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (124, 159, 'Gununglajang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (298, 152, 'Chichibu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (103, 137, 'Lerrnanist');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (341, 231, 'Cerenti');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (4, 166, 'Heret');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (356, 399, 'Tučepi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (254, 159, 'Kamalaputi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (120, 357, 'Sulahan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (85, 326, 'Senggapi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (256, 295, 'Puerto Obaldía');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (97, 321, 'Czerniewice');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (151, 238, 'Litian');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (187, 268, 'Talavera');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (318, 398, 'Bartolomé Masó');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (356, 216, 'Choco');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (24, 13, 'Kujung');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (256, 90, 'Itapecerica da Serra');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (144, 17, 'Mwense');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (217, 71, 'Smach Mean Chey');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (127, 192, 'Itaberaba');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (215, 367, 'Mitzpe Ramon');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (315, 89, 'Dolgoprudnyy');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (334, 300, 'Pantai Ceuremen');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (71, 263, 'Asino');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (170, 267, 'Pongol');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (155, 179, 'Karang Daye');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (10, 307, 'Bagamoyo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (110, 317, 'Esso');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (56, 208, 'Cipatujah');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (52, 122, 'Argalastí');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (21, 176, 'København');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (251, 259, 'Kraskino');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (58, 305, 'Aiguo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (121, 194, 'Stanovoye');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (37, 238, 'Eido');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (397, 121, 'Buenavista');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (99, 233, 'Raciążek');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (355, 102, 'Laslovo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (321, 87, 'Yuanqiao');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (203, 233, 'Jasaan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (260, 308, 'Novokuz’minki');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (144, 327, 'Cidade Velha');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (250, 150, 'Mansilingan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (300, 364, 'Uherce Mineralne');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (323, 354, 'Toyohashi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (324, 288, 'Machakos');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (337, 344, 'Suwa');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (347, 250, 'Chakwāl');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (49, 2, 'Chabařovice');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (53, 220, 'Cieplice Śląskie Zdrój');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (233, 245, 'Isdalstø');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (170, 226, 'Evinayong');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (380, 223, 'Yŏng-dong');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (74, 321, 'Rio de Moinhos');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (17, 214, 'Chợ Chu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (213, 254, 'Lolak');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (162, 160, 'Garešnica');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (393, 379, 'Abbeville');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (73, 243, 'Yuli');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (180, 355, 'Orsay');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (205, 13, 'Bingfang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (308, 284, 'Srokowo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (256, 145, 'Garça');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (185, 71, 'Yinjiaxi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (228, 377, 'T’azagyugh');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (42, 156, 'Doushaguan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (247, 207, 'Nama');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (137, 349, 'Dayton');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (107, 381, 'Saint-Pierre-des-Corps');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (31, 155, 'Angoulême');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (314, 185, 'Santiago');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (49, 200, 'Palmas');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (390, 393, 'Aubagne');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (295, 4, 'Suzano');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (144, 260, 'Nagbacalan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (132, 316, 'Blawi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (104, 397, 'Ujazd');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (58, 276, 'Nueva Vida Sur');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (202, 348, 'George Town');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (50, 80, 'Cimonyong');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (330, 322, 'Mörön');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (230, 255, 'Dongbatu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (124, 273, 'Shujāābād');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (354, 289, 'Hachinohe');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (162, 357, 'Sipe Sipe');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (174, 235, 'Mungwi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (389, 140, 'Tangchi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (144, 257, 'Magang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (89, 296, 'Xiacaoqiao');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (374, 62, 'Kota Bharu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (134, 37, 'Kanthararom');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (57, 361, 'Riolândia');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (316, 63, 'Didian');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (243, 220, 'Barbosa');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (122, 271, 'Thoeng');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (20, 361, 'Fengmu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (151, 315, 'São João da Barra');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (193, 137, 'Sufang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (375, 275, 'Hannover');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (377, 269, 'Tegalgunung');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (319, 125, 'Brunssum');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (196, 205, 'Otllak');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (235, 194, 'Xiaoshiqiao');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (376, 284, 'Iganga');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (243, 280, 'Qinglian');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (305, 220, 'Linggou');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (282, 306, 'Siennica Różana');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (73, 362, 'Pomacocha');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (327, 134, 'Kristiansand S');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (395, 30, 'Mislak');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (336, 336, 'Pulong Gubat');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (70, 358, 'Sankui');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (81, 347, 'Inowrocław');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (188, 35, 'Infanta');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (111, 274, 'Varėna');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (395, 66, 'Seattle');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (293, 18, 'Utsjoki');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (294, 48, 'Sanok');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (242, 282, 'Baş Göynük');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (394, 25, 'Czarków');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (374, 101, 'Denver');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (140, 8, 'Kindersley');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (220, 64, 'Sumberbening');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (49, 212, 'Łąka Prudnicka');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (213, 176, 'Wadi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (116, 99, 'Kimitsu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (336, 371, 'Borovan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (1, 170, 'La Esmeralda');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (132, 300, 'Igbo-Ukwu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (165, 59, 'Mont-Royal');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (18, 176, 'Goujie');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (359, 275, 'Rubik');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (83, 41, 'Libato');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (334, 263, 'Lincoln');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (397, 226, 'Duluth');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (199, 355, 'Yanyang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (143, 87, 'Marianowo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (258, 294, 'Anápolis');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (398, 110, 'Konstantynów Łódzki');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (264, 142, 'Al Mashāf');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (315, 354, 'Mílos');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (272, 359, 'Werasari');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (335, 296, 'Petushki');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (307, 229, 'Pochep');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (304, 87, 'Jieshou');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (9, 230, 'Turmus‘ayyā');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (195, 337, 'Puerto Madryn');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (9, 44, 'Bojonggenteng');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (157, 189, 'Sukabumi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (161, 62, 'As Salţ');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (143, 284, 'Limbuš');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (284, 61, 'Guoduwan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (132, 183, 'Zbąszyń');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (199, 275, 'Portela');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (119, 320, 'San Roque');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (159, 40, 'Dalo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (61, 60, 'Nugas');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (53, 297, 'Dukoh');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (15, 303, 'Ljupina');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (56, 370, 'Huazhou');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (248, 369, 'Ibaiti');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (174, 153, 'Inírida');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (58, 93, 'Jinping');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (320, 157, 'Alangalang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (63, 129, 'Dois Portos');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (256, 58, 'Krasnaye');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (356, 12, 'Manzë');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (69, 95, 'Yonghe');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (96, 222, 'Pulau Pinang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (342, 316, 'Moravský Krumlov');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (105, 131, 'Fornos de Algodres');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (395, 352, 'Phimai');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (155, 81, 'Hantsport');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (197, 320, 'Lorino');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (188, 320, 'Gongqiao');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (236, 391, 'Paris 03');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (254, 397, 'São Martinho de Árvore');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (48, 114, 'Podbrdo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (19, 4, 'Imielin');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (318, 43, 'Xinning');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (393, 75, 'Zākhū');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (37, 28, 'Villa Presidente Frei, Ñuñoa, Santiago, Chile');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (312, 82, 'Igir-igir');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (329, 25, 'Beijiang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (359, 386, 'Villa Mercedes');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (26, 334, 'Sancang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (285, 255, 'Tánh Linh');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (344, 141, 'Néa Manolás');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (106, 38, 'Sibanicú');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (399, 246, 'Chemnitz');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (152, 389, 'Barranca');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (380, 313, 'Mirandela');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (298, 160, 'Iracemápolis');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (247, 273, 'Taipalsaari');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (376, 9, 'Martanesh');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (30, 25, 'Guam Government House');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (145, 82, 'Khawr Fakkān');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (33, 316, 'Calabugao');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (253, 57, 'Shizong');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (173, 200, 'Luxi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (58, 283, 'Macau');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (189, 9, 'Aelande');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (209, 283, 'Monjas');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (23, 122, 'Loncoche');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (362, 244, 'Marechal Cândido Rondon');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (206, 16, 'Cane');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (41, 46, 'Muktāgācha');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (375, 377, 'Caomiao');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (137, 109, 'Tambakrejo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (69, 380, 'Lusong');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (349, 130, 'Qianjin');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (151, 223, 'Hukvaldy');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (215, 52, 'Weepangali');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (228, 286, 'Gujrāt');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (145, 55, 'Bamako');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (194, 173, 'Winton');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (350, 265, 'Łomazy');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (248, 154, 'Diang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (16, 306, 'Quinta da Courela');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (253, 229, 'Cinco Saltos');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (93, 318, 'Sopron');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (400, 268, 'Yangmadao');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (249, 352, 'Taourirt');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (218, 40, 'Uwelini');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (74, 132, 'Casal Velho');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (245, 346, 'Onguday');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (295, 281, 'Schaumburg');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (265, 151, 'Panevėžys');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (203, 321, 'Chaodi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (67, 5, 'Zherdevka');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (113, 101, 'Palamadu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (195, 207, 'Tutup');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (257, 208, 'Idenao');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (154, 202, 'Imus');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (359, 151, 'San Antonio');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (90, 67, 'Tomé Açu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (320, 215, 'Langxi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (310, 30, 'Albuquerque');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (25, 309, 'Korniyivka');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (178, 199, 'Peso da Régua');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (19, 263, 'Duoxiang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (216, 397, 'Lazaro Cardenas');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (222, 294, 'Burmakino');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (208, 197, 'Psygansu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (182, 183, 'Windusakti Hilir');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (271, 246, 'Nagrog Wetan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (324, 118, 'Severka');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (191, 305, 'Zango');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (262, 44, 'Sanshan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (392, 283, 'Nazarje');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (302, 275, 'Rantauambacang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (368, 35, 'Kameda-honchō');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (313, 171, 'Ulichnoye');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (114, 197, 'Shetan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (70, 50, 'Xiushi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (41, 64, 'Kuala Lumpur');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (173, 280, 'Lucija');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (144, 158, 'Yelets');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (203, 261, 'Hassi Berkane');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (193, 282, 'Libacao');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (25, 123, 'Baiyang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (142, 257, 'La Guata');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (253, 199, 'Tipolo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (252, 356, 'Runting');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (392, 92, 'Parang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (10, 117, 'Monte Azul Paulista');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (260, 238, 'Levallois-Perret');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (50, 136, 'Caballococha');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (111, 67, 'Daluo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (56, 31, 'Rosice');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (45, 83, 'Kachar');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (88, 141, 'Mörrum');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (64, 306, 'Cartagena');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (167, 255, 'Hasan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (397, 325, 'Jablonné nad Orlicí');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (323, 300, 'Al Qaryatayn');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (75, 235, 'Fengjiang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (345, 17, 'Ngajum');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (4, 54, 'Yashikera');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (103, 171, 'Buenaventura');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (293, 44, 'Orsha');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (110, 218, 'Noyal-sur-Vilaine');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (178, 275, 'El Paso');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (394, 157, 'Lyon');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (150, 231, 'Sysert’');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (374, 310, 'Malaya Purga');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (250, 345, 'Slavuta');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (153, 185, 'Galis');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (330, 43, 'Bucu Kidul');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (356, 232, 'Nenotes');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (41, 211, 'Uherce Mineralne');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (57, 33, 'Itapeva');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (221, 50, 'Poitiers');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (202, 394, 'Hutang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (262, 63, 'Yonghe');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (119, 27, 'Lokwabe');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (284, 187, 'Nagasaki-shi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (361, 249, 'Stalbe');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (83, 152, 'Dinjo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (204, 235, 'Svetlograd');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (82, 303, 'Medovene');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (395, 306, 'Pavlovsk');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (350, 163, 'Miass');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (64, 349, 'Kaliwates');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (311, 156, 'Beiyuan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (87, 19, 'Cametá');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (143, 266, 'Seversk');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (150, 317, 'Tulung');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (227, 226, 'Changping');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (156, 66, 'Lambayong');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (15, 294, 'Babakankadu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (244, 10, 'Kafr Nubl');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (330, 307, 'Phichit');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (384, 183, 'Huangshi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (347, 342, 'Drumcondra');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (209, 111, 'Jincheng');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (235, 320, 'Cachan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (289, 18, 'Tabant');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (338, 84, 'Sirte');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (398, 287, 'Tucdao');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (101, 170, 'Pirava');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (156, 301, 'Dayton');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (113, 111, 'Weihe');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (281, 192, 'Vostryakovo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (375, 204, 'Fernández');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (314, 376, 'Slobodnica');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (277, 290, 'Dolní Černilov');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (342, 35, 'Obrera');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (8, 12, 'Naka');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (147, 165, 'Plagiári');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (56, 291, 'Chuanpu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (289, 30, 'Blerim');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (58, 338, 'Jingmen');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (129, 142, 'Lingion');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (346, 312, 'Itsukaichi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (30, 307, 'Qingduizi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (100, 132, 'Znojmo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (124, 141, 'Labuhan Deli');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (99, 369, 'Tojeira');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (386, 31, 'Shibi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (49, 138, 'Aix-en-Provence');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (184, 318, 'Tomohon');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (133, 176, 'Strängnäs');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (96, 309, 'Camrose');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (330, 31, 'Longshan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (240, 63, 'Dabbūrīya');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (10, 151, 'Huangnaihai');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (371, 253, 'Alcabideche');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (149, 343, 'Mukō');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (54, 37, 'Sukoreno');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (57, 216, 'Cassanayan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (194, 156, '城郊');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (305, 166, 'Kertosari');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (385, 142, 'Yangxiang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (195, 383, 'Pervomayskoye');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (12, 253, 'Sūrāb');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (361, 134, 'Dubrava');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (226, 163, 'Whittier');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (43, 77, 'Phú Lộc');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (265, 314, 'Água Retorta');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (15, 86, 'Bouna');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (77, 79, 'Moss');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (325, 234, 'Stamáta');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (3, 268, 'Pizarro');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (95, 305, 'Matola');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (108, 142, 'Qiandong');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (8, 356, 'Dulce Nombre');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (296, 168, 'San Martín');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (196, 184, 'Arfará');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (141, 246, 'Montgomery');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (217, 310, 'Zagreb');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (170, 155, 'Krynice');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (383, 73, 'Norabats’');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (146, 358, 'Shatian');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (285, 232, 'Lubumbashi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (149, 212, 'Sukadana Selatan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (86, 372, 'Patabog');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (237, 303, 'Gongli');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (295, 386, 'Spas-Zaulok');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (172, 61, 'Lacdayan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (237, 331, 'Järfälla');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (95, 56, 'Los Fresnos');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (325, 351, 'Zhangqiang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (144, 382, 'Shuangta');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (257, 153, 'Oslo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (366, 38, 'El Rosario');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (249, 158, 'Morteros');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (305, 173, 'Chicoana');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (367, 309, 'Bethlehem');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (195, 18, 'Makato');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (268, 400, 'Tanda');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (8, 288, 'Aygeshat');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (40, 376, 'Huizhou');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (141, 211, 'Orléans');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (204, 48, 'Nyalindung');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (132, 247, 'San Kamphaeng');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (192, 197, 'Granadero Baigorria');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (57, 365, 'Garça');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (24, 366, 'Wołczyn');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (185, 164, 'Hradec Králové');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (395, 253, 'Ankou');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (333, 229, 'Valuyki');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (256, 66, 'Lhokkruet');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (38, 67, 'Yongping');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (187, 373, 'Pengjia Zhaizi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (384, 357, 'Złotoryja');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (334, 377, 'Onitsha');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (98, 60, 'El Sombrero');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (81, 185, 'Dyurtyuli');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (187, 258, 'Balkh');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (136, 202, 'Anguil');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (85, 215, 'Nanding');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (71, 189, 'Viangxai');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (217, 246, 'Hřebeč');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (119, 159, 'Hetian');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (376, 304, 'Verin Dvin');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (137, 51, 'Neqāb');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (253, 57, 'Kaura Namoda');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (128, 97, 'Tékane');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (88, 344, 'Bayrachky');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (242, 265, 'Cochrane');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (394, 394, 'Geneng');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (374, 93, 'Kibonsod');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (164, 263, 'Cilolohan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (180, 121, 'Novouzensk');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (161, 226, 'Salto de Pirapora');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (95, 361, 'Shetangpo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (165, 42, 'Markaz Mudhaykirah');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (198, 352, 'Toulouse');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (311, 41, 'Kuče');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (32, 110, 'Chong’ansi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (270, 375, 'Vilufushi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (135, 324, 'Jeffersonville');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (79, 335, 'Depapre');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (330, 235, 'Gembu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (69, 303, 'Orangeville');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (170, 295, 'Xinzhou');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (372, 273, 'Yanhu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (2, 378, 'Lindome');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (120, 197, 'Yelenendorf');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (289, 313, 'Tunguang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (83, 230, 'Camalote');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (142, 206, 'Gunung');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (108, 357, 'Mosjøen');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (4, 180, 'Solec-Zdrój');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (366, 172, 'Doko');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (121, 376, 'Curridabat');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (228, 349, 'Changshan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (176, 243, 'San Vicente');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (37, 88, 'Varkaus');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (125, 266, 'Pakxong');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (357, 369, 'Cogreg Wetan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (290, 122, 'Polo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (289, 106, 'Mahuta');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (264, 48, 'Kantyshevo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (14, 297, 'Hatu Buh');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (352, 25, 'Takahata');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (380, 364, 'Żyraków');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (323, 197, 'Vetlanda');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (127, 182, 'L’govskiy');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (218, 180, 'Nowa Dęba');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (262, 67, 'Morden');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (105, 173, 'Nagornyy');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (313, 48, 'Chenfangji');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (383, 331, 'Tiassalé');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (286, 196, 'Dongling');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (154, 285, 'Cinagrog Girang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (346, 345, 'Krupanj');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (332, 326, 'Kalapagada');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (60, 361, 'Piripiri');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (149, 244, 'Medovene');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (14, 224, 'Imaichi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (214, 297, 'Paris La Défense');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (260, 203, 'Tsiombe');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (277, 135, 'Morioka-shi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (303, 70, 'Baini');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (165, 282, 'Shangcunba');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (168, 156, 'Suai');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (142, 315, 'Tapada das Mercês');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (84, 131, 'Namibe');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (337, 89, 'Huazhou');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (336, 301, 'Buenavista');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (96, 258, 'Chinchero');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (231, 396, 'Versailles');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (207, 13, 'Sagua la Grande');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (388, 175, 'Dikson');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (392, 313, 'Luboń');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (11, 28, 'Kuafeu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (164, 300, 'San Francisco');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (93, 213, 'Hengfeng');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (236, 137, 'Gununggoong');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (314, 256, 'Fenghuo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (83, 108, 'Sandy Bay');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (392, 85, 'Arnhem');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (55, 281, 'Sovetskaya Gavan’');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (393, 210, 'São João del Rei');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (209, 171, 'Chaloem Phra Kiat');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (86, 91, 'Ruteng');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (140, 235, 'Kasembon');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (13, 180, 'Santa Maria');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (155, 213, 'Znamenskoye');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (28, 210, 'Bantal');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (337, 76, 'Svalöv');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (6, 349, 'Barţa‘ah ash Sharqīyah');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (305, 4, 'Daphu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (160, 233, 'El Triunfo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (95, 313, 'Blagoevgrad');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (166, 320, 'La Punta');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (64, 210, 'Ciudad Ojeda');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (298, 294, 'Buriti Alegre');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (297, 257, 'Garcia Hernandez');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (83, 158, 'Tenggun Dajah');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (167, 139, 'Tianzhou');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (193, 127, 'Otorohanga');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (272, 253, 'Kurnia');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (171, 60, 'Malian');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (278, 375, 'Kurungannyawa');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (124, 125, 'Xiaoshiqiao');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (196, 112, 'Yinjiacheng');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (193, 342, 'Isnā');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (238, 56, 'Na Klang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (102, 267, 'Shangqiu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (235, 363, 'Caridad');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (105, 224, 'Thị Trấn Việt Lâm');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (372, 227, 'Enjiang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (281, 75, 'Yongxing');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (177, 382, 'Khlong Sam Wa');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (283, 203, 'Samdrup Jongkhar');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (297, 204, 'Thames');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (240, 156, 'Manaoag');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (390, 267, 'Sindangbarang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (60, 167, 'Jhang Sadr');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (383, 145, 'Marondera');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (385, 270, 'Chisht-e Sharīf');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (2, 12, 'Hongxing');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (350, 90, 'Naju');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (140, 96, 'Las Matas de Santa Cruz');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (384, 277, 'Yongning');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (350, 27, 'Bailai');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (171, 21, 'Mauraro');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (271, 89, 'Plottier');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (231, 107, 'Chhāgalnāiya');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (181, 186, 'Dasha');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (44, 171, 'Staraya Mayna');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (1, 227, 'Palhais');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (210, 372, 'Sanjiazi');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (117, 354, 'Yangkang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (282, 334, 'Khorugh');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (269, 231, 'Vila Nova da Baronia');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (188, 167, 'Sapareva Banya');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (295, 237, 'Changsha');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (228, 247, 'Santa Lucía');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (365, 93, 'Malitubog');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (11, 59, 'Gwandu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (165, 320, 'Lanci Satu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (155, 248, 'Le Tampon');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (73, 72, 'Volgo-Kaspiyskiy');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (333, 121, 'Tanamiting');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (288, 21, 'Kyzylorda');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (7, 102, 'Pābna');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (21, 166, 'Barat');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (241, 87, 'Chencai');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (33, 339, 'Karangsari');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (260, 82, 'Kuala Terengganu');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (349, 70, 'Bergen');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (68, 30, 'Nizhniy Tsasuchey');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (258, 61, 'Curitiba');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (240, 79, 'Curug');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (328, 250, 'Fermelã');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (324, 339, 'Paços de Ferreira');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (323, 215, 'Gaotai');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (86, 53, 'Kalde Panga');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (384, 137, 'Ramon’');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (175, 191, 'Mersam');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (384, 148, 'Nishinoomote');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (187, 115, 'Sidem');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (397, 329, 'Mashizhai');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (367, 79, 'Ashchysay');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (325, 258, 'Rungkam');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (168, 264, 'Remedios');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (86, 158, 'Ruoqiang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (269, 204, 'Selaparang Timur');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (152, 62, 'Dongting');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (374, 258, 'Cela');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (274, 197, 'Yagoua');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (282, 304, 'Granada');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (107, 158, 'Itaberaba');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (220, 277, 'Zango');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (175, 201, 'Cikandang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (194, 4, 'Nanhe');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (354, 111, 'Aíyira');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (140, 388, 'Ostrožac');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (83, 287, 'Lewo');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (356, 363, 'Columbus');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (236, 54, 'Hailang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (171, 351, 'Dob');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (359, 220, 'Las Carreras');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (300, 152, 'Palon');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (34, 237, 'Vrdy');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (348, 354, 'Pehuajó');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (89, 105, 'Songfeng');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (391, 247, 'Lingbei');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (201, 197, 'Brak');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (15, 176, 'Youlongchuan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (136, 370, 'Odivelas');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (187, 268, 'Gaotian');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (261, 369, 'Jiufang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (64, 306, 'Falköping');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (372, 66, 'Shuangjiang');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (110, 358, 'Al Buţayḩah');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (96, 343, 'São Mateus');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (137, 371, 'Vojnić');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (353, 390, 'Çlirim');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (330, 324, 'Ribeira Grande');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (193, 291, 'Charlottetown');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (188, 133, 'Ebene');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (307, 197, 'Szynwałd');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (318, 200, 'Batan');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (172, 189, 'Jiaoxiyakou');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (10, 333, 'Tomigusuku');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (69, 43, 'Vazante');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (319, 229, 'Nogent-le-Rotrou');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (144, 279, 'Malasin');
insert into MatchInfo (TeamAID, TeamBID, Venue) values (362, 277, 'Lordelo');
